/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 18.0.0.Final (WildFly Core 10.0.0.Final) - 2.0.26.Final
 * Generated at: 2020-10-04 22:28:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"ru\">\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("  <meta name=\"keywords\" content=\"lab, prog, ifmo\" />\n");
      out.write("  <meta name=\"description\" content=\"Лаба 1 поп ПИПу\" />\n");
      out.write("  <link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("  <link href=\"img/icon.jpg\" rel=\"shortcut icon\" type=\"image/x-icon\" />\n");
      out.write("  <title>Лабораторная работа №2 по Веб-Программированию</title>\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"js/LabCheck.js\"></script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function() {\n");
      out.write("      $(\"button:button\").on('click', function() {\n");
      out.write("          var $checkbutton = $(this);\n");
      out.write("          var group = \"button:button[name='\" + $checkbutton.attr(\"name\") + \"']\";\n");
      out.write("          $(group).attr(\"disabled\", false);\n");
      out.write("          $checkbutton.attr(\"disabled\", true);\n");
      out.write("      });\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<header>\n");
      out.write("  <table id=\"header-table\">\n");
      out.write("    <tr>\n");
      out.write("      <td>\n");
      out.write("        <a id=\"logo\" class=\"name_class\">Лабораторная работа №2</a>\n");
      out.write("      </td >\n");
      out.write("      <td>\n");
      out.write("        <text id=\"about\" class=\"name_class\">\n");
      out.write("          Вариант - 10223\n");
      out.write("        </text>\n");
      out.write("      </td>\n");
      out.write("      <td>\n");
      out.write("        <img src=\"img/ifmo.png\" alt=\"Логотип итмо\" id=\"ifmo\" align=\"right\"/>\n");
      out.write("      </td >\n");
      out.write("    </tr>\n");
      out.write("  </table>\n");
      out.write("</header>\n");
      out.write("\n");
      out.write("<main>\n");
      out.write("  <table>\n");
      out.write("    <tr>\n");
      out.write("      <td>\n");
      out.write("        <svg width=\"800\" height=\"600\" xmlns=\"http://www.w3.org/2000/svg\">\n");
      out.write("          <!-- Created with Method Draw - http://github.com/duopixel/Method-Draw/ -->\n");
      out.write("          <g>\n");
      out.write("            <title>Layer 1</title>\n");
      out.write("            <path id=\"svg_37\" d=\"m199.65515,299.62284l199.65523,199.68755l0,-200.00002\" opacity=\"0.5\" fill-opacity=\"null\" stroke-width=\"NaN\" stroke=\"#000000\" fill=\"#00ffff\"/>\n");
      out.write("            <path id=\"svg_36\" d=\"m200.34481,299.62284c0,0 199.31037,-190.34485 199.31037,-190.34485c0,0 0,190.34485 0,190.34485\" opacity=\"0.5\" stroke-width=\"NaN\" stroke=\"#00ffff\" fill=\"#00ffff\"/>\n");
      out.write("            <rect id=\"svg_16\" height=\"200\" width=\"200\" y=\"299.62284\" x=\"399.65517\" stroke-width=\"0\" fill=\"#5fbf00\"/>\n");
      out.write("            <line id=\"svg_2\" y2=\"599.60936\" x2=\"400\" y1=\"0.32369\" x1=\"399.64286\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_3\" y2=\"200.32368\" x2=\"966.78567\" y1=\"199.60939\" x1=\"966.78567\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_4\" y2=\"300\" x2=\"700\" y1=\"300\" x1=\"100\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_6\" y2=\"15\" x2=\"385\" y1=\"0.32355\" x1=\"399.64284\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_7\" y2=\"15\" x2=\"385\" y1=\"0.32355\" x1=\"399.64284\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(-90 407.3215942382813,7.661773204803439) \" id=\"svg_11\" y2=\"15\" x2=\"400.00001\" y1=\"0.32355\" x1=\"414.64284\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(-90 692.3275146484376,291.9468383789063) \" id=\"svg_12\" y2=\"299.28582\" x2=\"685.00013\" y1=\"284.60936\" x1=\"699.64297\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_13\" y2=\"315.00003\" x2=\"685.00003\" y1=\"300.32358\" x1=\"699.64287\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line id=\"svg_14\" y2=\"315.00003\" x2=\"685.00003\" y1=\"300.32358\" x1=\"699.64287\" stroke-width=\"1.5\" stroke=\"#000\" fill=\"none\"/>\n");
      out.write("            <line stroke=\"#000000\" id=\"svg_17\" y2=\"290\" x2=\"599.65519\" y1=\"310\" x1=\"600\" fill=\"none\"/>\n");
      out.write("            <line stroke=\"#000000\" id=\"svg_18\" y2=\"290\" x2=\"499.65518\" y1=\"310\" x1=\"499.99999\" fill=\"none\"/>\n");
      out.write("            <line stroke=\"#000000\" id=\"svg_19\" y2=\"290\" x2=\"299.65516\" y1=\"310\" x1=\"299.99997\" fill=\"none\"/>\n");
      out.write("            <line stroke=\"#000000\" id=\"svg_20\" y2=\"290\" x2=\"199.65515\" y1=\"310\" x1=\"199.99996\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(90 399.82965087890625,390.3463439941407) \" stroke=\"#000000\" id=\"svg_23\" y2=\"380.34484\" x2=\"399.65517\" y1=\"400.34484\" x1=\"399.99998\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(90 399.8296508789063,500.00335693359375) \" stroke=\"#000000\" id=\"svg_24\" y2=\"490.00002\" x2=\"399.65517\" y1=\"510.00002\" x1=\"399.99998\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(90 399.8296508789063,190.3444519042969) \" stroke=\"#000000\" id=\"svg_25\" y2=\"180.34482\" x2=\"399.65517\" y1=\"200.34482\" x1=\"399.99998\" fill=\"none\"/>\n");
      out.write("            <line transform=\"rotate(90 399.82965087890625,109.65522766113286) \" stroke=\"#000000\" id=\"svg_26\" y2=\"99.65515\" x2=\"399.65517\" y1=\"119.65515\" x1=\"399.99998\" fill=\"none\"/>\n");
      out.write("            <path id=\"svg_28\" d=\"m199.65515,299.62284\" opacity=\"0.5\" fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"null\" stroke=\"#000000\" fill=\"none\"/>\n");
      out.write("            <path id=\"svg_30\" d=\"m199.65515,299.62284\" opacity=\"0.5\" fill-opacity=\"null\" stroke-opacity=\"null\" stroke-width=\"null\" stroke=\"#000000\" fill=\"none\"/>\n");
      out.write("            <path stroke=\"#000000\" id=\"svg_33\" d=\"m199.65514,299.27799c2.06897,-184.15903 200.68969,-189.65632 200.34489,-189.96765\" opacity=\"0.5\" stroke-opacity=\"null\" stroke-width=\"NaN\" fill=\"#00ffff\"/>\n");
      out.write("            <path id=\"svg_34\" d=\"m200.34481,299.62284\" opacity=\"0.5\" stroke-opacity=\"null\" stroke-width=\"NaN\" stroke=\"#000000\" fill=\"#00ffff\"/>\n");
      out.write("            <text xml:space=\"preserve\" text-anchor=\"start\" font-family=\"Helvetica, Arial, sans-serif\" font-size=\"24\" id=\"svg_38\" y=\"118.24351\" x=\"415.51724\" fill-opacity=\"null\" stroke-width=\"0\" stroke=\"#000000\" fill=\"#000000\">R</text>\n");
      out.write("            <text style=\"cursor: move;\" xml:space=\"preserve\" text-anchor=\"start\" font-family=\"Helvetica, Arial, sans-serif\" font-size=\"24\" id=\"svg_39\" y=\"198.24352\" x=\"415.51724\" fill-opacity=\"null\" stroke-width=\"0\" stroke=\"#000000\" fill=\"#000000\">R/2</text>\n");
      out.write("            <text style=\"cursor: move;\" xml:space=\"preserve\" text-anchor=\"start\" font-family=\"Helvetica, Arial, sans-serif\" font-size=\"24\" id=\"svg_40\" y=\"281.00215\" x=\"480.34484\" fill-opacity=\"null\" stroke-width=\"0\" stroke=\"#000000\" fill=\"#000000\">R/2</text>\n");
      out.write("            <text xml:space=\"preserve\" text-anchor=\"start\" font-family=\"Helvetica, Arial, sans-serif\" font-size=\"24\" id=\"svg_41\" y=\"281.00215\" x=\"590.00002\" fill-opacity=\"null\" stroke-width=\"0\" stroke=\"#000000\" fill=\"#000000\">R</text>\n");
      out.write("          </g>\n");
      out.write("        </svg>\n");
      out.write("      </td>\n");
      out.write("      <td>\n");
      out.write("        <form id=\"info-form\" name=\"info_form\" class=\"box\" onsubmit=\"return check(event)\" method=\"post\">\n");
      out.write("          <p>X: </p>\n");
      out.write("          ");
  for (int x = -3; x <= 5; x++) { 
      out.write("\n");
      out.write("              <button type=\"button\" name=\"x\" value=\"");
      out.print(x);
      out.write("\" id=\"x");
      out.print(x);
      out.write("\" class=\"button\">");
      out.print(x);
      out.write("</button>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <br/> <p>Y: </p> <input type=\"text\" name=\"Y-value\" id=\"Y-value\" maxlength=\"7\" placeholder=\" (-3;5) \">\n");
      out.write("          <br/>\n");
      out.write("          <p>R: </p>\n");
      out.write("          ");
  for (int x = 1; x <= 5; x++) { 
      out.write("\n");
      out.write("            <button type=\"button\" name=\"r\" value=\"");
      out.print(x);
      out.write("\" id=\"r");
      out.print(x);
      out.write("\" class=\"button\">");
      out.print(x);
      out.write("</button>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("          <br/>\n");
      out.write("          <input type=\"submit\" name=\"\" id=\"coordinates-submit\" value=\"Submit\"/>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("      </td>\n");
      out.write("    </tr>\n");
      out.write("  </table>\n");
      out.write("  <table id=\"data-table\" align=\"right\">\n");
      out.write("    <tr align=\"middle\">\n");
      out.write("      <td class=\"data-name\"> X </td>\n");
      out.write("      <td class=\"data-name\"> Y </td>\n");
      out.write("      <td class=\"data-name\"> R </td>\n");
      out.write("      <td class=\"data-name\"> RESULT </td>\n");
      out.write("      <td class=\"data-name\"> TIME </td>\n");
      out.write("      <td class=\"data-name\"> BENCHMARK </td>\n");
      out.write("    </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("  </table>\n");
      out.write("</main>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("  <text id=\"about\" >\n");
      out.write("    Провоторов Александр Владимирович, P3210, 2020\n");
      out.write("  </text>\n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
